### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by ionelmc** [rimraf/k#44]
Can speed be improved? Takes a full 1.35 second to run in in my project root. `git status` only takes 0.04 second.

**Comment by supercrabtree** [comment]
Yes. Currently git status is called on every file/directory, there is plans to rewrite this part of it so that git status is called only once, I just haven't got round to it yet.

Please have a stab at it if you like, pull requests are very welcome.

#31

**Comment by ionelmc** [comment]
Is this fixed now or?
