### ISSUE TITLE
Add new installation with zplug

### ISSUE THREAD

**Issue by b4b4r07** [rimraf/k#58]
Hi,

Your k is an amazing zsh plugin! I appreciate it.
BTW, by using [zplug](https://github.com/b4b4r07/zplug), we can easily install this plugin.

Would you add this installation method to your README?

```console
$ zplug "rimraf/k"
```

**Comment by simnalamburt** [comment]
:+1:

**Comment by supercrabtree** [comment]
Also dropped antigen from my personal dotfiles and now using zplug! great stuff :smile:

**Comment by b4b4r07** [comment]
:+1: Awesome, thanks!
